### ISSUE TITLE
大佬，帮忙看看iOS 10.3版本的bug，估计iOS 11以下都存在

### ISSUE THREAD

**Issue by ieliwb** [CrabMen/CMPageTitleView#10]
demo运行后，随便进一个，再点「跳转到详情」，返回，导航菜单一片空白，消失了

**Comment by ieliwb** [comment]
@CrabMen 拜托了

**Comment by CrabMen** [comment]
> demo运行后，随便进一个，再点「跳转到详情」，返回，导航菜单一片空白，消失了
谢谢反馈，正在找iOS10 以及iOS11的手机进行测试

**Comment by ieliwb** [comment]
> > demo运行后，随便进一个，再点「跳转到详情」，返回，导航菜单一片空白，消失了
> > 谢谢反馈，正在找iOS10 以及iOS11的手机进行测试

就你提供的demo也是这样

**Comment by CrabMen** [comment]
> > > demo运行后，随便进一个，再点「跳转到详情」，返回，导航菜单一片空白，消失了
> > > 谢谢反馈，正在找iOS10 以及iOS11的手机进行测试
> 
> 就你提供的demo也是这样
嗯嗯，好的

**Comment by CrabMen** [comment]
> > > > demo运行后，随便进一个，再点「跳转到详情」，返回，导航菜单一片空白，消失了
> > > > 谢谢反馈，正在找iOS10 以及iOS11的手机进行测试
> > 
> > 
> > 就你提供的demo也是这样
> > 嗯嗯，好的
刚找到一部10.3的手机，CMPageTitleContentView在进入详情页返会的时候约束发生改变，导致内部按钮向下偏移，目前正在找CMPageTitleContentView约束发生改变的原因（iOS 12 和iOS13暂未发现该问题）

**Comment by ieliwb** [comment]
> > > > > demo运行后，随便进一个，再点「跳转到详情」，返回，导航菜单一片空白，消失了
> > > > > 谢谢反馈，正在找iOS10 以及iOS11的手机进行测试
> > > 
> > > 
> > > 就你提供的demo也是这样
> > > 嗯嗯，好的
> > > 刚找到一部10.3的手机，CMPageTitleContentView在进入详情页返会的时候约束发生改变，导致内部按钮向下偏移，目前正在找CMPageTitleContentView约束发生改变的原因（iOS 12 和iOS13暂未发现该问题）

拜托了，着急发版，😁

**Comment by CrabMen** [comment]
@ieliwb 问题已修复，你使用0.6.2 版本试一下。如果使用的是旧版的cocoapods且搜索不到0.6.2的话，记得更新一下本地索引库

**Comment by ieliwb** [comment]
谢谢，谢谢，解决了
