### ISSUE TITLE
大佬，可以支持一下屏幕方向切换吗？

### ISSUE THREAD

**Issue by ieliwb** [CrabMen/CMPageTitleView#11]
![](https://pic.downk.cc/item/5e72c615e83c3a1e3a46dde9.png)

见上图，iPad 旋转下底部没有自适应高度，设置下面的后直接不显示视图
self.pageView.autoresizingMask = UIViewAutoresizingFlexibleWidth + UIViewAutoresizingFlexibleHeight;
，怎么解决呢，谢谢

**Comment by CrabMen** [comment]
@ieliwb 好的，兄弟，暗黑模式和支持屏幕旋转都排在需求上来着，无奈复工后工作一直比较紧张，你说的这个，我这几天呢抽时间看一下。

**Comment by MrJoexx** [comment]
> @ieliwb好的，兄弟，暗黑模式和支持屏幕旋转都排在需求上来着，无奈复工后工作一直比较紧张，你说的这个，我这几天呢抽时间看一下。

大佬  现在支持横屏了么  我这边使用的时候横屏后，竖屏回来还是会有点问题
