### ISSUE TITLE
大佬,你好.CMPageTitleView背景设置成透明,UITableViewCell的内容可否透过PageTitle显示出来,谢谢

### ISSUE THREAD

**Issue by cnfhv** [CrabMen/CMPageTitleView#16]

**Comment by CrabMen** [comment]
> _No description provided._
目前还是不支持的，后期可以关注一下，最近重构代码，你说的这个需求我也考虑到了，但是目前因为工作紧张，重构进度有些慢

**Comment by cnfhv** [comment]
你好，有什么好的想法思路给分享一下，谢谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: CrabMan <notifications@github.com&gt;
发送时间: 2020年5月13日 10:51
收件人: CrabMen/CMPageTitleView <CMPageTitleView@noreply.github.com&gt;
抄送: 小超 <281212504@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[CrabMen/CMPageTitleView] 大佬,你好.CMPageTitleView背景设置成透明,UITableViewCell的内容可否透过PageTitle显示出来,谢谢 (#16)





  
No description provided.
 目前还是不支持的，后期可以关注一下，最近重构代码，你说的这个需求我也考虑到了，但是目前因为工作紧张，重构进度有些慢

**Comment by CrabMen** [comment]
> 你好，有什么好的想法思路给分享一下，谢谢 发自我的iPhone

这个需求着急么？着急的话我抽时间更一个版本
如果只是单纯出于学习使用，我可以说一下大概的思路，因为最近实在是太忙了,qaq

**Comment by cnfhv** [comment]
您好，如果百忙中您能更新一版那将万分感谢🙏，如果不方便的话给分享一下思路也可以，再次感谢🙏



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: CrabMan <notifications@github.com&gt;
发送时间: 2020年5月13日 15:53
收件人: CrabMen/CMPageTitleView <CMPageTitleView@noreply.github.com&gt;
抄送: 小超 <281212504@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[CrabMen/CMPageTitleView] 大佬,你好.CMPageTitleView背景设置成透明,UITableViewCell的内容可否透过PageTitle显示出来,谢谢 (#16)






你好，有什么好的想法思路给分享一下，谢谢 发自我的iPhone

这个需求着急么？着急的话我抽时间更一个版本
如果只是单纯出于学习使用，我可以说一下大概的思路，因为最近实在是太忙了,qaq

**Comment by CrabMen** [comment]
> 您好，如果百忙中您能更新一版那将万分感谢🙏，如果不方便的话给分享一下思路也可以，再次感谢🙏 发自我的iPhone

嗯嗯，好的，你那边项目大概什么时候上线？给我一个时间，我抽时间更新一个版本

**Comment by cnfhv** [comment]
预计6月中旬，谢谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: CrabMan <notifications@github.com&gt;
发送时间: 2020年5月13日 16:53
收件人: CrabMen/CMPageTitleView <CMPageTitleView@noreply.github.com&gt;
抄送: 小超 <281212504@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[CrabMen/CMPageTitleView] 大佬,你好.CMPageTitleView背景设置成透明,UITableViewCell的内容可否透过PageTitle显示出来,谢谢 (#16)






您好，如果百忙中您能更新一版那将万分感谢🙏，如果不方便的话给分享一下思路也可以，再次感谢🙏 发自我的iPhone

嗯嗯，好的，你那边项目大概什么时候上线？给我一个时间，我抽时间更新一个版本

**Comment by CrabMen** [comment]
> 预计6月中旬，谢谢 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: CrabMan <notifications@github.com&gt; 发送时间: 2020年5月13日 16:53 收件人: CrabMen/CMPageTitleView <CMPageTitleView@noreply.github.com&gt; 抄送: 小超 <281212504@qq.com&gt;, Author <author@noreply.github.com&gt; 主题: 回复：[CrabMen/CMPageTitleView] 大佬,你好.CMPageTitleView背景设置成透明,UITableViewCell的内容可否透过PageTitle显示出来,谢谢 (#16) 您好，如果百忙中您能更新一版那将万分感谢🙏，如果不方便的话给分享一下思路也可以，再次感谢🙏 发自我的iPhone 嗯嗯，好的，你那边项目大概什么时候上线？给我一个时间，我抽时间更新一个版本 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

实在是不好意思，拖了这么久，目前最新的0.7.0版本是支持全屏模式的，并且已经在9x、10x、13x的真机上测试过了，具体使用方法可以参照demo中的 style02_03 方法
