### ISSUE TITLE
大佬你好，我想问下可不可以实现字体放大，并且还带下划线的功能呢？

### ISSUE THREAD

**Issue by AlianOL** [CrabMen/CMPageTitleView#17]
大佬你好，我想问下可不可以实现字体放大，并且还带下划线的功能呢？我看字体放大和下划线是在一个属性里。。所以想问下有没有实现方案

**Comment by CrabMen** [comment]
> 大佬你好，我想问下可不可以实现字体放大，并且还带下划线的功能呢？我看字体放大和下划线是在一个属性里。。所以想问下有没有实现方案
因为对应的类型是options类型，支持放大与下划线一起，我稍后给你贴代码哈

**Comment by CrabMen** [comment]
> 大佬你好，我想问下可不可以实现字体放大，并且还带下划线的功能呢？我看字体放大和下划线是在一个属性里。。所以想问下有没有实现方案

我刚看了一下示例图 _01-45.字体放大 && 下划线 - 颜色填充渐变_ 及其都是字体放大和下滑线同时存在的，你可以看下示例图中哪种效果和你说的接近，然后在demo工程的CMViewController.m 中找对应编好的代码即可。

**Comment by AlianOL** [comment]
> > 大佬你好，我想问下可不可以实现字体放大，并且还带下划线的功能呢？我看字体放大和下划线是在一个属性里。。所以想问下有没有实现方案
> 
> 我刚看了一下示例图 _01-45.字体放大 && 下划线 - 颜色填充渐变_ 及其下面部分的gif图，都是字体放大和下滑线同时存在的，你可以看下示例图中哪种效果和你说的接近，然后在demo工程的CMViewController.m 中找对应编号的代码即可(例如01-45图示效果，在CMViewController.m中的方法为-style01_45)。
哇，对不住大佬，是我没注意到，确实有，我再学习学习，多谢多谢

**Comment by CrabMen** [comment]
> > > 大佬你好，我想问下可不可以实现字体放大，并且还带下划线的功能呢？我看字体放大和下划线是在一个属性里。。所以想问下有没有实现方案
> > 
> > 
> > 我刚看了一下示例图 _01-45.字体放大 && 下划线 - 颜色填充渐变_ 及其下面部分的gif图，都是字体放大和下滑线同时存在的，你可以看下示例图中哪种效果和你说的接近，然后在demo工程的CMViewController.m 中找对应编号的代码即可(例如01-45图示效果，在CMViewController.m中的方法为-style01_45)。
> > 哇，对不住大佬，是我没注意到，确实有，我再学习学习，多谢多谢

如果问题已解决，可以将问题关闭
