### ISSUE TITLE
显示上有bug

### ISSUE THREAD

**Issue by zhangAoLong** [CrabMen/CMPageTitleView#18]
下载demo
随便一个模式 在切换上面的菜单选择器时会导致下面的tableview高度变化。（通过点击和左右滑动引起不一样的高度变化）

**Comment by CrabMen** [comment]
> 下载demo
> 随便一个模式 在切换上面的菜单选择器时会导致下面的tableview高度变化。（通过点击和左右滑动引起不一样的高度变化）

我今晚测试一下，之前没发现过这样的问题；测试完成以后我告诉你结果

**Comment by AlianOL** [comment]
> 下载demo
> 随便一个模式 在切换上面的菜单选择器时会导致下面的tableview高度变化。（通过点击和左右滑动引起不一样的高度变化）

我也遇到了相同的问题，每个标签对应的控制器里的tableview，滑动过去，tableview高度没问题，如果是点击过去，tableview最上方会漏出mjrefresh的UI，我一会录个视频，保存个链接给你，求大佬看下

**Comment by AlianOL** [comment]
CMpageTitleView https://v.douyin.com/JNEVpSe/ 复制此链接，打开【抖音短视频】，直接观看视频！大概就是这样

**Comment by AlianOL** [comment]
> > 下载demo
> > 随便一个模式 在切换上面的菜单选择器时会导致下面的tableview高度变化。（通过点击和左右滑动引起不一样的高度变化）
> 
> 我今晚测试一下，之前没发现过这样的问题；测试完成以后我告诉你结果

我刚才又看了下，确实你给的demo也存在这个问题，但是我看了下源码，你也没咋操作控制器的UI，没有头绪，

**Comment by CrabMen** [comment]
> 我刚才又看了下，确实你给的demo也存在这个问题，但是我看了下源码，你也没咋操作控制器的UI，没有头绪，

辛苦录的视频，我抽时间demo中集成一下mjrefresh 看看问题出在哪里
