### ISSUE TITLE
Exception	NSException *	"cm_config属性不能为空"	0x00000002818eee50

### ISSUE THREAD

**Issue by wnzq1314** [CrabMen/CMPageTitleView#19]
这需要配置什么属性呢

**Comment by CrabMen** [comment]
> 这需要配置什么属性呢

`
CMPageTitleView *pageView = [[CMPageTitleView alloc] initWithFrame:frame];
    pageView.delegate = self;
    
    CMPageTitleConfig *config = [CMPageTitleConfig defaultConfig];
    config.cm_childControllers = self.childControllers; //必传参数
//需要将CMPageTitleConfig对象赋值给CMPageTitleView的属性cm_config赋值
    pageView.cm_config = config;
    [self.view addSubview:pageView];
`
