### ISSUE TITLE
不能改动titleView的背景颜色(cm_backgroundColor无效)

### ISSUE THREAD

**Issue by SyKingW** [CrabMen/CMPageTitleView#4]
版本: 0.3.1
看了一下代码, 是有提供 cm_backgroundColor , 但是并没有真正使用这个属性

ps: 另外, 作者最好也能加上一个设置背景图片

**Comment by CrabMen** [comment]
谢谢老哥看的这么细，最近这段时间会更新一个版本，在修复背景色配置的同时也会加上另外一个朋友说的右侧视图的功能
