### ISSUE TITLE
能不能支持懒加载，不用一下子把全部页面全部加载出来

### ISSUE THREAD

**Issue by Wjy1005** [CrabMen/CMPageTitleView#5]
能不能支持懒加载，不用一下子把全部页面全部加载出来

**Comment by VineFiner** [comment]
你把设置颜色的那个注释掉，不在主屏幕的就不会调用 viewDidLoad 了。

**Comment by Wjy1005** [comment]
> 你把设置颜色的那个注释掉，不在主屏幕的就不会调用 viewDidLoad 了。

可以具体说下是哪个属性吗，我是直接调用
CMPageTitleConfig *config = [CMPageTitleConfig defaultConfig];

**Comment by VineFiner** [comment]
> > 你把设置颜色的那个注释掉，不在主屏幕的就不会调用viewDidLoad了。
> 
> 可以具体说下是哪个属性吗，我是直接
> 调用CMPageTitleConfig * config = [CMPageTitleConfig defaultConfig];

我不是很明白你说的懒加载是什么意思。

当你alloc并init了一个ViewController时，这个ViewController应该是还没有创建view的。

ViewController的view是使用了lazyInit方式创建，就是说你调用的view属性的getter：［self view］。在getter里会先判断view是否创建，如果没有创建，那么会调用loadView来创建view。loadView完成时会继续调用viewDidLoad。loadView和viewDidLoad的一个区别就是：loadView时还没有view。而viewDidLoad时view以及创建好了。
https://www.cnblogs.com/xjy-123/p/5271063.html

**Comment by VineFiner** [comment]
一般情况下，我们会在 viewDidLoad 中执行一些方法，比如网络请求，添加子视图什么的。这个完全没有问题。
你说的这个懒加载有什么意图？节省内存占用吗？先说需求，再确认方法。

**Comment by Wjy1005** [comment]
> > > 你把设置颜色的那个注释掉，不在主屏幕的就不会调用viewDidLoad了。
> > 
> > 
> > 可以具体说下是哪个属性吗，我是直接
> > 调用CMPageTitleConfig * config = [CMPageTitleConfig defaultConfig];
> 
> 我不是很明白你说的懒加载是什么意思。
> 
> 当你alloc并init了一个ViewController时，这个ViewController应该是还没有创建view的。
> 
> ViewController的view是使用了lazyInit方式创建，就是说你调用的view属性的getter：［self view］。在getter里会先判断view是否创建，如果没有创建，那么会调用loadView来创建view。loadView完成时会继续调用viewDidLoad。loadView和viewDidLoad的一个区别就是：loadView时还没有view。而viewDidLoad时view以及创建好了。
> https://www.cnblogs.com/xjy-123/p/5271063.html

明白了，谢谢
