### ISSUE TITLE
To do:子控制器的生命周期不可控！

### ISSUE THREAD

**Issue by XiaoWuTongZhi** [CrabMen/CMPageTitleView#6]
issue：子控制器的生命周期不可控，例如当从1滑到2时，2如果已经加载过就不会走viewWillAppear，1也不会走viewWillDisappear，因此你需要增加一个子控制器遵循的协议来手动维护他们的生命周期。

**Comment by CrabMen** [comment]
> issue：子控制器的生命周期不可控，例如当从1滑到2时，2如果已经加载过就不会走viewWillAppear，1也不会走viewWillDisappear，因此你需要增加一个子控制器遵循的协议来手动维护他们的生命周期。
终于有时间把生命周期的管理弄一下了，0.6.1版本中管理了childController的生命周期

**Comment by XiaoWuTongZhi** [comment]
> > issue：子控制器的生命周期不可控，例如当从1滑到2时，2如果已经加载过就不会走viewWillAppear，1也不会走viewWillDisappear，因此你需要增加一个子控制器遵循的协议来手动维护他们的生命周期。
> > 终于有时间把生命周期的管理弄一下了，0.6.1版本中管理了childController的生命周期
